export const BookingDataArray = [
  {
    id: 1,
    firstName: "Liucien",
    lastName: "Obrien",
    date: "11 Aug 2022 9:00 PM",
    avatar: "/illustrations/NewestBookingCards/LucianObrien.png",
    bookingDuration: "3 days 2 nights",
    guestsPersons: "5 Guests",
    isHot: false,
    bookingCosts: "72",
    photo: "/illustrations/NewestBookingCards/Obrien.png",
  },
  {
    id: 2,
    firstName: "Harrison",
    lastName: "Stein",
    date: "09 Aug 2022 7:00 PM",
    avatar: "/illustrations/NewestBookingCards/HarrisonStein.png",
    bookingDuration: "3 days 2 nights",
    guestsPersons: "3 Person",
    isHot: false,
    bookingCosts: "72",
    photo: "/illustrations/NewestBookingCards/Harrison.png",
  },
  {
    id: 3,
    firstName: "Jayvion",
    lastName: "Simon",
    date: "12 Aug 2022 10:00 PM",
    avatar: "/illustrations/NewestBookingCards/JayvionSimon.png",
    bookingDuration: "3 days 2 nights",
    guestsPersons: "1 Person",
    isHot: false,
    bookingCosts: "72",
    photo: "/illustrations/NewestBookingCards/Jayvion.png",
  },
  {
    id: 4,
    firstName: "Deja",
    lastName: "Brady",
    date: "10 Aug 2022 8:00 PM",
    avatar: "/illustrations/NewestBookingCards/DejaBrady.png",
    bookingDuration: "3 days 2 nights",
    guestsPersons: "5 Guests",
    isHot: true,
    bookingCosts: "72",
    photo: "/illustrations/NewestBookingCards/Deja.png",
  },
];
