/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Example API
 * Documentation for Example API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiChartStatistic200Item = {
  amt?: number;
  name?: string;
  pv?: number;
  uv?: number;
};
