/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Example API
 * Documentation for Example API
 * OpenAPI spec version: 1.0.0
 */

export * from "./getApiChartStatistic200Item";
export * from "./getApiChartTotalIncome200Item";
export * from "./getApiChartTours200Item";
export * from "./postApiAuthLogin200";
export * from "./postApiAuthLoginBody";
export * from "./postApiAuthRegister200";
export * from "./postApiAuthRegisterBody";
